import whois

domain_country_map = {
    ".ac": "Ascension Adası",
    ".ad": "Andorra",
    ".ae": "Birleşik Arap Emirlikleri",
    ".af": "Afganistan",
    ".ag": "Antigua ve Barbuda",
    ".ai": "Anguilla",
    ".al": "Arnavutluk",
    ".am": "Ermenistan",
    ".an": "Hollanda Antilleri",
    ".ao": "Angola",
    ".aq": "Antarktika",
    ".ar": "Arjantin",
    ".as": "Amerikan Samoası",
    ".at": "Avusturya",
    ".au": "Avustralya",
    ".aw": "Aruba",
    ".az": "Azerbaycan",
    ".ba": "Bosna-Hersek",
    ".bb": "Barbados",
    ".bd": "Bangladeş",
    ".be": "Belçika",
    ".bf": "Burkina Faso",
    ".bg": "Bulgaristan",
    ".bh": "Bahreyn",
    ".bi": "Burundi",
    ".bj": "Benin",
    ".bm": "Bermuda",
    ".bn": "Brunei Darussalam",
    ".bo": "Bolivya",
    ".br": "Brezilya",
    ".bs": "Bahamalar",
    ".bt": "Bhutan",
    ".bv": "Bouvet Adası",
    ".bw": "Botswana",
    ".by": "Beyaz Rusya",
    ".bz": "Belize",
    ".ca": "Kanada",
    ".cc": "Cocos (Keeling) Adaları",
    ".cd": "Kongo Demokratik Cumhuriyeti",
    ".cf": "Orta Afrika Cumhuriyeti",
    ".cg": "Kongo Cumhuriyeti",
    ".ch": "İsviçre",
    ".ci": "Fildişi Sahili",
    ".ck": "Cook Adaları",
    ".cl": "Şili",
    ".cm": "Kamerun",
    ".cn": "Çin, anakara",
    ".co": "Kolombiya",
    ".coop": "cooperatives",
    ".cr": "Costa Rika",
    ".cu": "Küba",
    ".cv": "Cape Verde",
    ".cx": "Christmas Adası",
    ".cy": "Kıbrıs",
    ".cz": "Çek Cumhuriyeti",
    ".de": "Almanya",
    ".dj": "Jibuti",
    ".dk": "Danimarka",
    ".dm": "Dominika",
    ".do": "Dominik Cumhuriyeti",
    ".dz": "Cezayir",
    ".ec": "Ekvador",
    ".ee": "Estonya",
    ".eg": "Mısır",
    ".er": "Eritre",
    ".es": "İspanya",
    ".et": "Etiyopya",
    ".fi": "Finlandiya",
    ".fj": "Fiji",
    ".fk": "Falkland Adaları",
    ".fm": "Micronezya",
    ".fo": "Faroe Adaları",
    ".fr": "Fransa",
    ".ga": "Gabon",
    ".gb": "Birleşik Krallık",
    ".gd": "Grenada",
    ".ge": "Gürcistan",
    ".gf": "Fransız Guyanası",
    ".gg": "Guernsey",
    ".gh": "Gana",
    ".gi": "Gibraltar",
    ".gl": "Greenland",
    ".gm": "Gambia",
    ".gn": "Gine",
    ".gp": "Guadeloupe",
    ".gq": "Equator Ginesi",
    ".gr": "Yunanistan",
    ".gs": "Güney Georgia ve Güney Sandwich Adaları",
    ".gt": "Guatemala",
    ".gu": "Guam",
    ".gw": "Guinea-Bissau",
    ".gy": "Guyana",
    ".hk": "Hong Kong",
    ".hm": "Heard Adası ve McDonald Adaları",
    ".hn": "Honduras",
    ".hr": "Hırvatistan",
    ".ht": "Haiti",
    ".hu": "Macaristan",
    ".id": "Endonezya",
    ".ie": "İrlanda",
    ".il": "İsrail",
    ".im": "Isle of Man",
    ".in": "Hindistan",
    ".io": "Hint Okyanusundaki İngiliz Toprakları",
    ".iq": "Irak",
    ".ir": "İran",
    ".is": "İzlanda",
    ".it": "İtalya",
    ".je": "Jersey",
    ".jm": "Jamaika",
    ".jo": "Ürdün",
    ".jp": "Japonya",
    ".ke": "Kenya",
    ".kg": "Kırgızistan",
    ".kh": "Kamboçya",
    ".ki": "Kiribati",
    ".km": "Komor",
    ".kn": "Saint Kitts ve Nevis",
    ".ko": "Kosova",
    ".kr": "Güney Kore Cumhuriyeti",
    ".kw": "Kuveyt",
    ".ky": "Cayman Adaları",
    ".kz": "Kazakistan",
    ".la": "Laos",
    ".lb": "Lübnan",
    ".lc": "Saint Lucia",
    ".li": "Liechtenstein",
    ".lk": "Sri Lanka",
    ".lr": "Liberia",
    ".ls": "Lesotho",
    ".lt": "Litvanya",
    ".lu": "Lüksemburg",
    ".lv": "Letonya",
    ".ly": "Libya",
    ".ma": "Fas",
    ".mc": "Monako",
    ".md": "Moldova",
    ".me": "Karadağ",
    ".mg": "Madagaskar",
    ".mh": "Marshall Adaları",
    ".mk": "Makedonya",
    ".ml": "Mali",
    ".mm": "Myanmar",
    ".mn": "Moğolistan",
    ".mo": "Macau",
    ".mp": "Kuzey Mariana Adaları",
    ".mq": "Martinik",
    ".mr": "Moritanya",
    ".ms": "Montserrat",
    ".mt": "Malta",
    ".mu": "Mauritius",
    ".mv": "Maldivler",
    ".mw": "Malawi",
    ".mx": "Meksika",
    ".my": "Malezya",
    ".mz": "Mozambik",
    ".na": "Namibya",
    ".name": "Kişisel",
    ".nc": "Yeni Kaledonya",
    ".ne": "Nijer",
    ".nf": "Norfolk Adası",
    ".ng": "Nijerya",
    ".ni": "Nikaragua",
    ".nl": "Hollanda",
    ".no": "Norveç",
    ".np": "Nepal",
    ".nr": "Nauru",
    ".nu": "Niue",
    ".nz": "Yeni Zelanda",
    ".om": "Umman",
    ".pa": "Panama",
    ".pe": "Peru",
    ".pf": "Fransız Polonezyası",
    ".pg": "Papua Yeni Gine",
    ".ph": "Filipinler",
    ".pk": "Pakistan",
    ".pl": "Polonya",
    ".pm": "Saint-Pierre ve Miquelon",
    ".pn": "Pitcairn Adaları",
    ".pr": "Porto Riko",
    ".ps": "Filistin",
    ".pt": "Portekiz",
    ".pw": "Palau",
    ".py": "Paraguay",
    ".qa": "Katar",
    ".re": "Réunion",
    ".ro": "Romanya",
    ".rs": "Sırbistan",
    ".ru": "Rusya",
    ".rw": "Rwanda",
    ".sa": "Suudi Arabistan",
    ".sb": "Solomon Adaları",
    ".sc": "Seyşeller",
    ".sd": "Sudan",
    ".se": "İsveç",
    ".sg": "Singapur",
    ".sh": "Saint Helena",
    ".si": "Slovenya",
    ".sj": "Svalbard ve Jan Mayen Adaları",
    ".sk": "Slovakya",
    ".sl": "Sierra Leone",
    ".sm": "San Marino",
    ".sn": "Senegal",
    ".so": "Somali",
    ".sr": "Surinam",
    ".st": "São Tomé ve Príncipe",
    ".su": "eski Sovyetler Birliği",
    ".sv": "El Salvador",
    ".sy": "Suriye",
    ".sz": "Svaziland",
    ".tc": "Turks ve Caicos Adaları",
    ".td": "Çad",
    ".tf": "Antartika’daki Fransız toprakları",
    ".tg": "Togo",
    ".th": "Tayland",
    ".tj": "Tacikistan",
    ".tk": "Tokelau",
    ".tl": "Timor-Leste",
    ".tm": "Türkmenistan",
    ".tn": "Tunus",
    ".to": "Tonga",
    ".tp": "Doğu Timor",
    ".tr": "Türkiye",
    ".tt": "Trinidad ve Tobago",
    ".tv": "Tuvalu",
    ".tw": "Çin Cumhuriyeti (Tayvan)",
    ".tz": "Tanzanya",
    ".ua": "Ukrayna",
    ".ug": "Uganda",
    ".uk": "Birleşik Krallık",
    ".um": "United States Minor Outlying Islands",
    ".us": "Amerika Birleşik Devletleri",
    ".uy": "Uruguay",
    ".uz": "Özbekistan",
    ".va": "Vatikan",
    ".vc": "Saint Vincent ve Grenadinler",
    ".ve": "Venezuela",
    ".vg": "Birleşik Krallık Virgin Adaları",
    ".vi": "ABD Virgin Adaları",
    ".vn": "Vietnam",
    ".vu": "Vanuatu",
    ".wf": "Wallis ve Futuna",
    ".ws": "Samoa",
    ".ye": "Yemen",
    ".yt": "Mayotte",
    ".yu": "Yugoslavya",
    ".za": "Güney Afrika",
    ".zm": "Zambiya",
    ".zw": "Zimbabve"
}

def get_whois_info(domain):
    
    try:

        whois_info = whois.whois(domain)
        # print("whois_info", whois_info)
        country = whois_info.country if whois_info and 'country' in whois_info else None
        # print("country111", country)
        


        if not country:
            domain_extension = '.' + domain.split('.')[-1]
            country = domain_country_map.get(domain_extension, "Bilinmiyor")
            # print("country2222", country)
        
        return country 
     
    except Exception as e:
        print("WHOIS Hatası:", e)
        return "Bilinmiyor..."